fixtures:
    symlinks:
      file_upload: "#{source_dir}"
    repositories:
      stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
      tea: https://github.com/icann-dns/puppet-tea.git
      logrotate:
        repo: https://github.com/icann-dns/puppet-logrotate
        ref: v1.4.0-ICANN-1
    forge_modules:
